import type { Metadata } from "next";
import { Epilogue } from 'next/font/google'
import localFont from 'next/font/local'
import "./globals.css";

const epilogue = Epilogue({
  subsets: ['latin'],
  variable: '--font-epilogue',
})

const clashDisplay = localFont({
  src: '../public/fonts/ClashDisplay-Variable.woff2',
  variable: '--font-clash-display',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${epilogue.variable} ${clashDisplay.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
